-- ============================================================
-- Happy Scoopers - Base de datos fuente (OLTP) en PostgreSQL
-- Traducción del proyecto SQL Server HappyScoopers_Demo
-- Convenciones: snake_case, timestamp, boolean, IDENTITY
-- ============================================================

CREATE SCHEMA IF NOT EXISTS oltp;
SET search_path TO oltp;

-- ---------- Geografía ----------
CREATE TABLE countries (
    country_id      int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    country_name    varchar(60)  NOT NULL,
    formal_name     varchar(60)  NOT NULL,
    country_code    varchar(3),
    population      bigint,
    continent       varchar(30)  NOT NULL,
    region          varchar(30)  NOT NULL,
    subregion       varchar(30)  NOT NULL,
    modified_date   timestamp    NOT NULL DEFAULT now()
);

CREATE TABLE provinces (
    province_id     int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    province_code   varchar(5)   NOT NULL,
    province_name   varchar(200) NOT NULL,
    country_id      int          NOT NULL,
    population      bigint,
    modified_date   timestamp    NOT NULL DEFAULT now()
);

CREATE TABLE cities (
    city_id         int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    city_name       varchar(50)  NOT NULL,
    province_id     int          NOT NULL,
    population      bigint,
    modified_date   timestamp    NOT NULL DEFAULT now()
);

CREATE TABLE addresses (
    address_id      int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    address_line1   varchar(60)  NOT NULL,
    address_line2   varchar(60),
    city_id         int          NOT NULL,
    postal_code     varchar(15)  NOT NULL,
    modified_date   timestamp    NOT NULL DEFAULT now()
);

-- ---------- Personas y tiendas ----------
CREATE TABLE customers (
    customer_id          int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name           varchar(50)  NOT NULL,
    last_name            varchar(100) NOT NULL,
    full_name            varchar(151) GENERATED ALWAYS AS (first_name || ' ' || last_name) STORED,
    title                varchar(30)  NOT NULL,
    delivery_address_id  int          NOT NULL,
    billing_address_id   int          NOT NULL,
    phone_number         varchar(24)  NOT NULL,
    email                varchar(100),
    modified_date        timestamp    NOT NULL DEFAULT now()
);

CREATE TABLE employees (
    employee_id     int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    last_name       varchar(100) NOT NULL,
    first_name      varchar(100) NOT NULL,
    title           varchar(25)  NOT NULL,
    birth_date      timestamp    NOT NULL,
    gender          char(10)     NOT NULL,
    hire_date       timestamp    NOT NULL,
    job_title       varchar(100) NOT NULL,
    address_id      int          NOT NULL,
    manager_id      int         ,
    modified_date   timestamp    NOT NULL DEFAULT now()
);

CREATE TABLE stores (
    store_id        int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name            varchar(200) NOT NULL,
    manager_id      int         ,
    address_id      int          NOT NULL,
    modified_date   timestamp    NOT NULL DEFAULT now()
);

-- ---------- Catálogo de productos ----------
CREATE TABLE product_departments (
    department_id   int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name            varchar(50)  NOT NULL,
    description     varchar(200) NOT NULL,
    modified_date   timestamp    NOT NULL DEFAULT now()
);

CREATE TABLE product_categories (
    category_id           int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category_name         varchar(15)  NOT NULL,
    category_description  varchar(200) NOT NULL,
    department_id         int          NOT NULL,
    modified_date         timestamp    NOT NULL DEFAULT now()
);

CREATE TABLE product_subcategories (
    product_subcategory_id   int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_category_id      int          NOT NULL,
    subcategory_name         varchar(200) NOT NULL,
    subcategory_description  varchar(200) NOT NULL,
    modified_date            timestamp    NOT NULL DEFAULT now()
);

CREATE TABLE units_of_measure (
    unit_of_measure_id  int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    unit_measure_code   char(3)     NOT NULL,
    name                varchar(50) NOT NULL,
    modified_date       timestamp   NOT NULL DEFAULT now()
);

CREATE TABLE products (
    product_id           int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_name         varchar(40)   NOT NULL,
    product_code         varchar(10)   NOT NULL,
    product_description  varchar(200)  NOT NULL,
    subcategory_id       int           NOT NULL,
    unit_of_measure_id   int           NOT NULL,
    unit_price           numeric(18,2) NOT NULL,
    discontinued         boolean       NOT NULL,
    modified_date        timestamp     NOT NULL DEFAULT now()
);

-- ---------- Ingredientes, recetas e inventario ----------
CREATE TABLE ingredients (
    ingredient_id       int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ingredient_name     varchar(200),
    unit_of_measure_id  int,
    modified_date       timestamp NOT NULL DEFAULT now()
);

CREATE TABLE recipes (
    recipe_id       int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id      int           NOT NULL,
    ingredient_id   int           NOT NULL,
    quantity        numeric(18,2) NOT NULL,
    comments        varchar(2000) NOT NULL,
    modified_date   timestamp     NOT NULL DEFAULT now(),
    valid_from      timestamp(0)  NOT NULL,
    valid_to        timestamp(0)  NOT NULL
);

CREATE TABLE package_types (
    package_type_id    int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    package_type_name  varchar(50) NOT NULL,
    modified_date      timestamp   NOT NULL DEFAULT now()
);

CREATE TABLE inventory_items (
    inventory_item_id         int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id                int,
    ingredient_id             int,
    package_type_id           int           NOT NULL,
    unit_of_measure_id        int           NOT NULL,
    quantity                  numeric(18,2) NOT NULL,
    barcode                   varchar(50),
    vat_rate                  numeric(18,3) NOT NULL,
    unit_price                numeric(18,2) NOT NULL,
    recommended_retail_price  numeric(18,2),
    typical_weight_per_unit   numeric(18,3) NOT NULL,
    modified_date             timestamp     NOT NULL DEFAULT now()
);

CREATE TABLE inventory_transactions (
    inventory_transaction_id  int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    inventory_item_id         int           NOT NULL,
    customer_id               int          ,
    order_id                  int,
    transaction_date          timestamp     NOT NULL,
    quantity                  numeric(18,3) NOT NULL,
    modified_date             timestamp     NOT NULL DEFAULT now()
);

-- ---------- Transaccional ----------
CREATE TABLE payment_types (
    payment_type_id    int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    payment_type_name  varchar(50) NOT NULL,
    modified_date      timestamp   NOT NULL DEFAULT now()
);

CREATE TABLE promotions (
    promotion_id         int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    deal_description     varchar(30)   NOT NULL,
    start_date           date          NOT NULL,
    end_date             date          NOT NULL,
    discount_amount      numeric(18,2),
    discount_percentage  numeric(18,3),
    modified_date        timestamp     NOT NULL DEFAULT now()
);

CREATE TABLE orders (
    order_id             int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id          int,
    employee_id          int       NOT NULL,
    delivery_address_id  int       NOT NULL,
    payment_type_id      int       NOT NULL,
    order_date           timestamp NOT NULL,
    delivery_date        timestamp NOT NULL,
    comments             text,
    status               int,
    modified_date        timestamp NOT NULL DEFAULT now()
);

-- Nota: en el origen OrderLines no tenía PK. Aquí agregamos una,
-- pero el grano de negocio sigue siendo (order_id, line_number).
CREATE TABLE order_lines (
    order_line_id      int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id           int           NOT NULL,
    product_id         int           NOT NULL,
    package_type_id    int           NOT NULL,
    promotion_id       int          ,
    inventory_item_id  int          ,
    unit_price         numeric(18,2) NOT NULL,
    description        varchar(200)  NOT NULL,
    quantity           int           NOT NULL,
    discount           numeric(18,2) NOT NULL,
    modified_date      timestamp     NOT NULL DEFAULT now(),
    line_number        varchar(10),
    vat_rate           numeric(18,2)
);

